---
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: https://api.github.com:443/repos/joelmoss/strano?access_token=somerandomstring
    body: 
    headers:
      user-agent:
      - Github Ruby Gem 0.3.3
      content-type:
      - application/x-www-form-urlencoded
      authorization:
      - Token token="somerandomstring"
      accept-encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/1.0.4
      date:
      - Tue, 13 Dec 2011 11:46:15 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      status:
      - 200 OK
      x-ratelimit-limit:
      - '5000'
      etag:
      - ! '"bf4b4e8dd00769b57dafc2f6063b971b"'
      x-oauth-scopes:
      - repo, user
      x-ratelimit-remaining:
      - '4988'
      x-accepted-oauth-scopes:
      - repo, public_repo
      content-encoding:
      - gzip
    body: !binary |-
      H4sIAAAAAAAAA41Ty46cMBD8F0u5MYB5zY6lKDnlA6I95YIM7gFnwEZue0fJ
      av897cA8MoqyOSAZ213VVV1+ZaPEVtmzmaxUyIR3ARJ2tO5EPzxhiGMb3MQE
      G7T/TN8YurS3s/huYZotYobeSWNTOmIJO0vfj+DW2kmaIcgBqPhr6H7Q8SzR
      g2s7quhHJkyYpoSNfp42jtH7BUWW3XiyBx4CUYC904vX1hAybUQJZ33Sl+7x
      xTzg0U5scOv9L5hRMBNHOSGpXwKOoFrpCb7IOd/xYpfvn3Muai7ywzei7B1I
      /+edfFfmz3wvilqUZbxDhDfr/ilqM29x+oVQr32MdoZl9Y/gUP+ko6J4Sphd
      wLQaMQAZnZOt2jnrVrLVU208DI7AHrymQYNj4pVJYpJbCU1gtR2hDw5SKvx9
      GuecrcusOkJZq31T7suqOMimU+pQFk1XQ9epmtef1McLiiyqpxRSeZKz1KkB
      n0lE8Hg3gQ/FFz2TMqTFhe1+veNVni5mINlr+K7Yi74fZEDK2nWcdFsrJqqG
      V+T+JqKNW+y99ql0soOOgboEjr0lzMg5pneN+HvNOFjsrZntXcSsTNbAfwd8
      y0JY1GPA7kLI8xiwqKxo9g0vKQPxEVwiER/x2y+L/gOH2wMAAA==
    http_version: '1.1'
